name: aosny_services
description: A new Flutter project.

version: 1.0.8+10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  intl:
  json_annotation: ^3.0.1
  dio: ^3.0.10
  http:
  percent_indicator: ^2.1.6
  connectivity: ^0.4.9+2
  splashscreen: ^1.2.0
  rflutter_alert: ^1.0.5
  fluttertoast: ^7.0.4
  shared_preferences: ^0.5.10
  modal_progress_hud: ^0.1.3
  signature: 3.2.0
  flutter_bloc: ^6.0.5
  equatable: ^1.2.5
  url_launcher: ^5.5.3
  package_info: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/logo/
